from os import environ

VAULT_ADDR = environ['VAULT_ADDR']
SLACK_TOKEN = environ["REPORTER_SLACK_BEARER"]
SLACK_REPORT_CHANNEL = environ["SLACK_CHANNEL"]
SLACK_MONITORING_CHANNEL = environ["SLACK_MONITORING_CHANNEL"]
KUBERNETES_AUTH_MOUNTPOINT = environ["KUBERNETES_AUTH_MOUNTPOINT"]
KUBERNETES_AUTH_ROLE = environ["KUBERNETES_AUTH_ROLE"]
NOTIFY_SLACK= True
HUMAN_ROLES = ["developer", "admin", "root", "devops"]
NUMBER_OF_DAYS_FOR_A_TOKEN_BE_CONSIDERED_LONG_LIVED=7
NUMBER_OF_DAYS_FOR_A_LONG_LIVED_TOKEN_TO_NOTICE_EXPIRATION=30
ALERT_THRESHOLD_ON_SAME_ID_HAVING_MANY_TOKENS=30
WORK_DAYS=[0,1,2,3,4]
WORK_HOURS=[8,9,10,11,12,13,14,15,16,17,18]